<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>create_rule</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>35d058a7-7bca-426a-b48e-5ff5e70618c0</testSuiteGuid>
   <testCaseLink>
      <guid>47ec8ac2-d8a1-4368-af85-b92f2ac6db6b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/create_rule/Login_logout/Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>1d10a0a1-ff0a-4e33-9176-4b76653f40b7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/create_rule/Automation/create_success</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3fd5bcd6-fe46-4851-b32e-56a101ed3df7</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/rule/create_success</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>3fd5bcd6-fe46-4851-b32e-56a101ed3df7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>title</value>
         <variableId>f3a784a0-9820-4701-9f17-112b8def222a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3fd5bcd6-fe46-4851-b32e-56a101ed3df7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>trigger</value>
         <variableId>1ce7a28e-9e88-4b06-a969-1da9cc199c40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3fd5bcd6-fe46-4851-b32e-56a101ed3df7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>rule_group_id</value>
         <variableId>c300f871-3c24-4c61-93a5-3505c35e5385</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3fd5bcd6-fe46-4851-b32e-56a101ed3df7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>stop_processing</value>
         <variableId>67577f77-0502-4887-9a89-ef2d8dc782e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3fd5bcd6-fe46-4851-b32e-56a101ed3df7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>strict</value>
         <variableId>b4bb8e73-c628-4b76-8c87-852ef1c91320</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3fd5bcd6-fe46-4851-b32e-56a101ed3df7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>description</value>
         <variableId>e850b44d-c74f-434b-ba4b-94f095f6352e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3fd5bcd6-fe46-4851-b32e-56a101ed3df7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>triggers[type]</value>
         <variableId>314954cf-0f64-4d87-8e1d-f55ef6576092</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3fd5bcd6-fe46-4851-b32e-56a101ed3df7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>triggers[prohibited]</value>
         <variableId>4afcfa47-60f9-42c8-9cbe-3db1d61bbea5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3fd5bcd6-fe46-4851-b32e-56a101ed3df7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>triggers[value]</value>
         <variableId>651b3d58-0f71-47e3-9e4d-af2f6c36f6ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3fd5bcd6-fe46-4851-b32e-56a101ed3df7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>trigger-stop-processing</value>
         <variableId>1a6355fe-6921-4fb8-acec-1fd7140c8904</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3fd5bcd6-fe46-4851-b32e-56a101ed3df7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>actions[type]</value>
         <variableId>874ef88b-4b26-4daa-9407-2a67a506377d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3fd5bcd6-fe46-4851-b32e-56a101ed3df7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>actions[value]</value>
         <variableId>87e565f5-a00c-475a-8a32-b61f13def154</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3fd5bcd6-fe46-4851-b32e-56a101ed3df7</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>actions[stop_processing]</value>
         <variableId>36ab3a1c-ca98-4a12-99fd-7203c4eb6a19</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c576ea59-5023-411d-96c9-9dd04988987b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/create_rule/Automation/fail_title_exist</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c407ad1-03ff-4e14-8c75-a3fa8725ca53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8cd2c162-80c5-4fa0-8058-8acb7c9a9e04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd5fc040-896a-4b16-8459-3cbbd0f4fe17</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7df67643-cfe1-4bbf-b0d6-66fd179a33ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65306b37-58b9-40fd-ae3c-ee5414cfb96c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99d1e19e-46f4-4c4e-99a1-d831a2b9212a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>db30730b-0fd4-4fa7-92bc-1f55cf72fed9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7d00d65-10e1-49be-be81-0fa1674afbf1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7db4f60-c1c0-4ecd-863e-4db6ed18276b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edba8ff2-4d98-4716-ad2a-85a42198e733</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7280cd89-f981-4309-b66b-904ac19b5d4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4939fa6b-b22b-411d-97bc-a3a431919089</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40d6a844-d87a-4921-bd77-5cb9c826b1ce</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7a77b450-fed7-476b-8285-918bfe9e177e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/create_rule/Automation/fail_title_empty</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>175ae118-106c-4f09-97b5-ec657670ac55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a221e4d-0ac3-4a9b-bfcf-2a580f8e5b70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3ebc3c5-1c9a-448d-a135-2de6a735cb0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a4a9185-d681-40cc-bded-94abacc021fd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fa847a10-e02c-47dc-a33e-f58b2dfc0552</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90446f64-7bde-41e4-b199-39316ae87d37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d847a3f9-66a8-4176-8470-ef70ab42be13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>477220b5-47b8-43c9-99cf-5d7b8a0b312c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1bd1079e-74c7-4a3a-bd05-55315e60672a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8c733bb-0fb9-417e-b58f-009bb41d7c33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de9300bf-25c4-4632-a949-db7a33ea34bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e8d7e5e-777a-4ec8-bee0-c0d14fdfcf3a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56bdf716-5497-48a5-a2b8-a79bb2a714fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cdb650cc-129d-473b-bdb9-44ddf3310145</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/create_rule/Automation/fail_title_101</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f750f758-8051-4278-94ee-1997a3bc7b9f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>150f0bf4-a91d-426d-8615-8a910460778b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aef011b4-6c5b-49ea-94a1-52c4f4dae5c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d7a5b39-ce7e-4cfc-8fa5-5e67626e622e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e152337-a25b-4625-97cf-c80c789ed1f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcb2b991-3189-4c79-9fc2-233b7ce18b06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60f55c4a-c5e7-498f-a245-87f0c2e9516d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e470c2bd-01b3-42e1-8731-ed710184c286</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab559249-2bac-4e17-8c63-2f868bb2e7d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6054e0cc-bfa0-4f4f-8bac-1ce79400bc8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd7c5b8d-1f2f-4efa-a34e-7db552797725</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3242e764-04c1-4722-ba9e-57b4bf3b3156</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ff7f496a-0659-4a2e-91e4-3b2c7cc93b40</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e00c2dee-2d4f-4339-ace2-2aa07a945698</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/create_rule/Automation/fail_trigger_value</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>539e6358-825b-481c-8688-8d734464f228</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>426e732c-5b74-4240-827c-57611bc6a0a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c28e5ca-ff05-4485-8f17-c0298185490e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64b22147-8020-418c-a040-3dcab02c2b06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec1975d2-d150-4d58-ae30-80e919faeaeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0336f5d9-1465-4be1-913f-f8986dae89c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cac4746-160d-4735-b6be-ececf4c1295b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ce19dcb-1f1e-4ebb-bb89-d050d3485a81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccce0ef7-5ba7-49d1-bb7a-6f102fd8e3c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf22486c-e846-4536-aa9e-30c0ad50e03b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d94b6863-d1fb-4cd5-a864-0defc5ec2f8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d10b39a5-16ad-4a03-af7e-3676a608f38b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06989e97-f150-440d-97e6-77d2c319b3f4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9bdbefd2-cadd-426d-a1da-e064f6de3585</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/create_rule/Automation/fail_action_value</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1e30609-e3f9-4183-a88e-e1df80fb8c30</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14ab262d-3e6c-4284-abc0-e5e84d035838</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dcd18ba9-6523-4536-8bec-3ed106e4136e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16e7a248-1c3b-4ef1-ae68-4357aa20efa6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1dae518-dad1-427c-80b9-b3f042d4fbb7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3dee0b2-d75f-4288-8197-2fce62b82a4f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c93739d5-f50b-4bbc-8fdd-971268cced5f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3dcd88e8-3e26-4450-a52e-337d138928fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c13d9f9-57a2-4a35-afd9-a5ef139f5cd0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8efe0c53-8faa-484c-9a53-fe49d5091d2e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e41bb60d-ed78-4685-b373-075ac1d1ebb2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>107407f7-5853-4d53-896b-2a11be80ec18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e12b2d36-ec28-48cf-80b1-b27621c747aa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8a1c5c02-c6f1-4117-99ed-87aa32f09529</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/create_rule/Login_logout/Logout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
