<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Budgets</name>
   <tag></tag>
   <elementGuidId>173d22bf-ec31-4306-be59-613f53ec4c7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='budget-menu']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#budget-menu > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3844a9aa-7e32-47d3-a1f5-67428246da35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://firefly.buudadawg.online/budgets</value>
      <webElementGuid>cbfa0d7b-036a-4605-92b9-4e741b43a386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            
            Budgets
        </value>
      <webElementGuid>a1e35e5c-1ff3-409a-b793-733bec98ed2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;budget-menu&quot;)/a[1]</value>
      <webElementGuid>6b1a5076-5b2b-41be-b9d7-f9531c0494e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='budget-menu']/a</value>
      <webElementGuid>e41077b5-2561-4996-9933-11cff3f963a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://firefly.buudadawg.online/budgets')]</value>
      <webElementGuid>64765c9e-2b65-46ba-9957-4d8e42449314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>35327534-0579-403f-8a1f-3e7b407d93c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://firefly.buudadawg.online/budgets' and (text() = '
            
            Budgets
        ' or . = '
            
            Budgets
        ')]</value>
      <webElementGuid>743aee13-cec4-454e-8377-c46adc21bcdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
