<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Transactions</name>
   <tag></tag>
   <elementGuidId>c404a881-1bf6-443b-a823-8b18d8383a73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='transaction-menu']/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#transaction-menu > a > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9a4f6ba0-a6ec-4711-a41b-34bd78031f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transactions</value>
      <webElementGuid>cd4ff07e-16e9-4b6d-b120-57caabd05e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transaction-menu&quot;)/a[1]/span[1]</value>
      <webElementGuid>49295a5c-795e-4a62-b6b3-9133c99530b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='transaction-menu']/a/span</value>
      <webElementGuid>d48f0925-9384-43b1-960e-3dcac6f3c3a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a/span</value>
      <webElementGuid>89a0eaed-5241-4caa-a79f-24eaeb927763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Transactions' or . = 'Transactions')]</value>
      <webElementGuid>4ad3472b-92bf-4c40-9e1c-3285704bec35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
