<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_select_extra_option</name>
   <tag></tag>
   <elementGuidId>34d64bcd-2227-4c9c-9b4a-4877455e56e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='extra-options']/div/div/span/div/ul/li[2]/a/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > a > label.checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>518bb46d-dc34-42ad-bd48-462707367ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2b9effce-0f0e-4450-a8bb-9eb154f17290</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> huybank</value>
      <webElementGuid>5cd24fe2-0319-4865-ae96-edaeb5531670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;extra-options&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/span[@class=&quot;multiselect-native-select&quot;]/div[@class=&quot;btn-group open&quot;]/ul[@class=&quot;multiselect-container dropdown-menu&quot;]/li[3]/a[1]/label[@class=&quot;checkbox&quot;]</value>
      <webElementGuid>3b742343-ba6e-4975-a9b9-a4ae44ab229f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='extra-options']/div/div/span/div/ul/li[3]/a/label</value>
      <webElementGuid>ba466559-9559-489f-ab65-cc5eb5fd70ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/span/div/ul/li[3]/a/label</value>
      <webElementGuid>ba7eb6bf-3f76-43dc-9b86-b9fb7091d063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' huybank' or . = ' huybank')]</value>
      <webElementGuid>d1cd456e-635a-4d78-89d2-b50c4c3a93ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
