<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delete_trash_button</name>
   <tag></tag>
   <elementGuidId>10402e8f-c0ec-488b-9c1f-7d59ab48da75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-fw.fa-trash-o</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/section[2]/div/div/div/div[2]/table/tbody/tr/td/div/a[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c0ad6804-0447-42f0-84b1-ff40e7523ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-fw fa-trash-o</value>
      <webElementGuid>28cabb24-2426-4c94-a996-ccf1924e499c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;content-wrapper&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;box-body no-padding&quot;]/table[@class=&quot;table table-responsive  table-hover sortable&quot;]/tbody[1]/tr[1]/td[@class=&quot;hidden-sm hidden-xs&quot;]/div[@class=&quot;btn-group btn-group-xs edit_tr_buttons&quot;]/a[@class=&quot;btn btn-danger btn-xs&quot;]/span[@class=&quot;fa fa-fw fa-trash-o&quot;]</value>
      <webElementGuid>7732da9e-17a0-4ef5-ad07-12aa15f7d8d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/section[2]/div/div/div/div[2]/table/tbody/tr/td/div/a[2]/span</value>
      <webElementGuid>b9aedd09-cdf0-4cfa-a3f3-16648bd8ce55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>4a5eab90-0c05-42cb-8344-be348cecea76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
