<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_New rule</name>
   <tag></tag>
   <elementGuidId>d591be31-3556-4029-a664-2280acd724cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(2) > a.btn.btn-success.new_rule</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@href, 'https://firefly.buudadawg.online/rules/create/12')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>182f9145-0910-4ea4-ba07-6a982f08bb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://firefly.buudadawg.online/rules/create/12</value>
      <webElementGuid>4aa751e1-ec44-4eb1-8489-e28ea6221c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success new_rule</value>
      <webElementGuid>78398f13-a529-4041-8569-7a5e79917a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New rule</value>
      <webElementGuid>1428d881-20ce-41fe-b9de-56e788eb895c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;content-wrapper&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12&quot;]/div[@class=&quot;box rules-box&quot;]/div[@class=&quot;box-body&quot;]/p[2]/a[@class=&quot;btn btn-success new_rule&quot;]</value>
      <webElementGuid>87f104d3-574f-4d2f-90d3-80ffd4c0cf43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/section[2]/div[3]/div/div/div[2]/p[2]/a</value>
      <webElementGuid>3bfa551a-d894-4395-b0e7-66c0db7450a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'New rule')])[3]</value>
      <webElementGuid>4f3650be-ec3f-4a7d-a2ec-cb5e14835c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//div[@id='app']/div/section[2]/div[3]/div/div/div[2]/p[2]/a</value>
      <webElementGuid>629bd4ab-21fe-46cd-816e-040c31c701cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/a</value>
      <webElementGuid>ae702e33-1167-4d9a-841c-a3cae3e5df4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://firefly.buudadawg.online/rules/create/12' and (text() = 'New rule' or . = 'New rule')]</value>
      <webElementGuid>c9800bdb-cf57-4b6c-a9a7-80466ac692db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
