<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delete_trash_button</name>
   <tag></tag>
   <elementGuidId>62d573ef-28be-4c24-8ef7-62c2d3633287</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-danger > span.fa.fa-fw.fa-trash</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@title = 'Delete' and @class = 'btn btn-danger']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f2052c93-3894-41d2-909f-a15aedee22e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-fw fa-trash</value>
      <webElementGuid>1a62c311-3b7e-4cc3-90dc-883e622c55f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;content-wrapper&quot;]/section[@class=&quot;content&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12&quot;]/div[@class=&quot;box rules-box&quot;]/div[@class=&quot;box-body&quot;]/table[@class=&quot;table table-hover table-striped group-rules&quot;]/tbody[@class=&quot;rule-connected-list ui-sortable&quot;]/tr[@class=&quot;single-rule&quot;]/td[2]/div[@class=&quot;btn-group btn-group-xs edit_buttons&quot;]/a[@class=&quot;btn btn-danger&quot;]/span[@class=&quot;fa fa-fw fa-trash&quot;]</value>
      <webElementGuid>25b6e9d7-a23a-4afe-9b3c-cd6675d10643</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/section[2]/div[3]/div/div/div[2]/table/tbody/tr/td[2]/div/a[2]/span</value>
      <webElementGuid>14f9b50b-f108-4250-9b18-d02c29a91c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>a8f55bb3-9163-4222-a83e-3b8fa3008406</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
