<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Logout</name>
   <tag></tag>
   <elementGuidId>42d19c75-84df-42bf-9c29-42700ccfc77b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.logout-link > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/aside/section/ul/li[15]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e31daa60-6f2e-4a6b-a512-30835c5373b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>248c7044-8f70-4aa8-9eb9-86fe9599c12e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/aside[@class=&quot;main-sidebar&quot;]/section[@class=&quot;sidebar&quot;]/ul[@class=&quot;sidebar-menu tree&quot;]/li[15]/a[@class=&quot;logout-link&quot;]/span[1]</value>
      <webElementGuid>c2e4d779-1e52-4ced-b91f-50b2543437f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/aside/section/ul/li[15]/a/span</value>
      <webElementGuid>7d2b9603-476f-441d-8b00-2d6709cec558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[15]/a/span</value>
      <webElementGuid>a9c115f4-eed3-434e-8ea4-3dd5c8b0295d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>eec463f3-cf98-4994-ba90-2e36639d1a4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
