<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Withdrawal</name>
   <tag></tag>
   <elementGuidId>224fa52e-e70c-49b1-9c39-384102ae7f2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.switch-button.btn-default</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='name_holder']/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>29abe7ce-07f3-43a7-80c5-0831a9f283da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>0a4431d2-9028-4286-9f2a-9cc7cf08214a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn switch-button btn-default</value>
      <webElementGuid>a9e3c461-fa1b-4b9a-80fe-c6b1c29e668d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>withdrawal</value>
      <webElementGuid>5ed60e08-0746-43f8-8a78-95228149d9fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Withdrawal</value>
      <webElementGuid>30d75086-8968-4d10-8de7-3a69c04eb24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name_holder&quot;)/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;btn-group btn-group-sm&quot;]/a[@class=&quot;btn switch-button btn-default&quot;]</value>
      <webElementGuid>78e49eef-d957-4571-b5d5-7f37b2bf8e2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='name_holder']/div/div/a</value>
      <webElementGuid>632ed6c6-a1aa-44df-a699-46c1fae7895d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Withdrawal')]</value>
      <webElementGuid>df04ee48-d862-4344-910a-59db09d55c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[10]</value>
      <webElementGuid>4e47a815-bd11-4de4-87d0-f03ae3066562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>d736b396-5b7f-4249-9b9c-71fb6e1a3f3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Withdrawal' or . = 'Withdrawal')]</value>
      <webElementGuid>7d0a965a-46f4-49ee-be44-6d73896fabab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
