<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_create_another</name>
   <tag></tag>
   <elementGuidId>21fe034b-92be-43cd-b953-0fcda2645dbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='recurrence_return_to_form']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#recurrence_return_to_form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82386809-36b2-42a3-bbaa-9d4724502263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7a6abde3-a4c8-4c4a-9622-e2e178171b7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>create_another</value>
      <webElementGuid>bb0d8452-56ce-46fb-b88d-2f25fe8dac69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recurrence_return_to_form</value>
      <webElementGuid>d119cb3a-b07a-4a28-babc-b732bd6d0048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>45d66a95-bbab-44ef-844f-c1ce9bd882d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recurrence_return_to_form&quot;)</value>
      <webElementGuid>61cd2bdb-fd1e-4230-a739-11a75e1df9d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='recurrence_return_to_form']</value>
      <webElementGuid>f52e8bd8-bffb-40f4-8fd5-30ddfb746756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='store']/div[3]/div/div/div[2]/div/div/div/label/input</value>
      <webElementGuid>1e10184f-0d5c-4089-80d0-aaf4c09c944e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/label/input</value>
      <webElementGuid>4fb90209-acad-4a37-9f01-2d79f02d2b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'create_another' and @id = 'recurrence_return_to_form']</value>
      <webElementGuid>37a8142b-0d19-422d-855a-b8149f8c81c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
