<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_weekend</name>
   <tag></tag>
   <elementGuidId>333dcbd9-81f5-477d-a895-e53e02565a67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_weekend</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_weekend']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a3025ee4-7847-4324-8328-07260961c816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>71427686-b925-41d1-9030-e530d2ab4c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>weekend</value>
      <webElementGuid>7cd80485-cd68-4d5c-873f-199489c12b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_weekend</value>
      <webElementGuid>cdddde57-f1d0-4b13-aa84-3a195472504a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>02f29fe3-5ede-468a-95a1-47caacb988c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d9b1b9ad-f084-47ef-b502-672b23607a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Just create the transactionSkip the occurrenceCreate the transaction on the previous Friday insteadCreate the transaction on the next Monday instead</value>
      <webElementGuid>39ecf95b-ac37-4ebf-8fe3-30d64ef9b722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_weekend&quot;)</value>
      <webElementGuid>41ea5ea9-fd5d-4e27-a7a5-92326780ef7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_weekend']</value>
      <webElementGuid>ae1be0a7-b5b4-41b8-88d0-2108086e0a4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='weekend_holder']/div/select</value>
      <webElementGuid>0c3f7a45-88aa-47dd-93b6-0d61cf1c0d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>3b1be5d6-142f-4b35-9bca-852d707695bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'weekend' and @id = 'ffInput_weekend' and (text() = 'Just create the transactionSkip the occurrenceCreate the transaction on the previous Friday insteadCreate the transaction on the next Monday instead' or . = 'Just create the transactionSkip the occurrenceCreate the transaction on the previous Friday insteadCreate the transaction on the next Monday instead')]</value>
      <webElementGuid>daaa9bd6-40c4-4d73-8426-a4eca9570f18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
