<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_repetition_type</name>
   <tag></tag>
   <elementGuidId>966665b0-bb49-43a3-9ee8-6f436e34b9d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_repetition_type</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_repetition_type']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>077ab9b1-ac07-4d48-9aeb-fe9a7a260727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>cc432186-ab36-42f3-aceb-8efae5c7de60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repetition_type</value>
      <webElementGuid>b7440be7-5140-450f-8d2a-f48cffcc65f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_repetition_type</value>
      <webElementGuid>30cc6063-91fe-4163-824e-94577904c071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>10476df1-83b0-4c9d-baa2-0f2272ed36c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3b81cf32-2258-42b2-b447-e3d398195e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Every dayEvery week on WednesdayEvery month on the 3(st/nd/rd/th) dayEvery month on the 1(st/nd/rd/th) WednesdayEvery year on January 3rd</value>
      <webElementGuid>a1b88e74-4ab1-4e93-9d14-2cc422306a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_repetition_type&quot;)</value>
      <webElementGuid>e99417d5-2f39-4c60-bbe0-8450b61f0d81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_repetition_type']</value>
      <webElementGuid>b69aef6e-cb18-4dd6-86d3-aa549ac34e3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='repetition_type_holder']/div/select</value>
      <webElementGuid>88ee416a-26f4-4c30-983e-d4e9ba9fa8bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>50fe25bd-57c5-435d-8d8d-283225ac7f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'repetition_type' and @id = 'ffInput_repetition_type' and (text() = 'Every dayEvery week on WednesdayEvery month on the 3(st/nd/rd/th) dayEvery month on the 1(st/nd/rd/th) WednesdayEvery year on January 3rd' or . = 'Every dayEvery week on WednesdayEvery month on the 3(st/nd/rd/th) dayEvery month on the 1(st/nd/rd/th) WednesdayEvery year on January 3rd')]</value>
      <webElementGuid>6e4ec0e8-b6a9-4cb0-b0d2-e38bfa5efce6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
