<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_repetition_ends</name>
   <tag></tag>
   <elementGuidId>306e378a-a70c-4bf2-82e6-315a0a8212fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_repetition_end</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_repetition_end']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5915e67b-f30d-4916-a0df-ba6343fa1707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b5060e22-abb8-460c-80a2-9f2021c914a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repetition_end</value>
      <webElementGuid>cd42c440-daec-4f1c-8171-81d7a6b71d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_repetition_end</value>
      <webElementGuid>be3793b0-ca68-4579-95e0-e4095edb0f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bd4253eb-bbd5-48da-8bdc-1c9a01308fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>09652fa0-8ace-4204-b48b-3dc0b49d0860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Repeat foreverRepeat until dateRepeat a number of times</value>
      <webElementGuid>de58bb58-879d-4aa2-91d9-ef6b6a2ca973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_repetition_end&quot;)</value>
      <webElementGuid>6ccc6f2a-25ee-4f8f-abe5-59db2e77e097</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_repetition_end']</value>
      <webElementGuid>2826c438-7604-417e-85b2-20cef79bdcff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='repetition_end_holder']/div/select</value>
      <webElementGuid>b3ea0745-9847-4866-af35-c7f11c947539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/select</value>
      <webElementGuid>cc314ffe-6604-4709-beec-022a392393a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'repetition_end' and @id = 'ffInput_repetition_end' and (text() = 'Repeat foreverRepeat until dateRepeat a number of times' or . = 'Repeat foreverRepeat until dateRepeat a number of times')]</value>
      <webElementGuid>e500c034-0534-430f-9731-aff24ca44af1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
