<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_huybankhuybank ti khon tit kimV tin mt</name>
   <tag></tag>
   <elementGuidId>d694534d-903f-494f-b8d2-3b599f79b4be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_account_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_account_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f53d18a6-6468-4d46-ab1e-f7beea32b068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3e2237da-9b0f-4ebc-a1d0-b17c7413e50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account_id</value>
      <webElementGuid>67af7326-2000-4821-9beb-b37fd2ea9c81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_account_id</value>
      <webElementGuid>d797df1d-80ac-409d-bca7-92b5e3f8d39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>df6d8016-3658-4118-943d-61e34b323cce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bc5463c4-35f2-4ea7-a545-2ca0aa6bbe59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>huybankhuybank tài khoản tiết kiệmVí tiền mặt</value>
      <webElementGuid>fe002627-e172-46f3-b7cc-00823a8403ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_account_id&quot;)</value>
      <webElementGuid>abd2bb91-eb38-4422-9ee5-db1965652211</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_account_id']</value>
      <webElementGuid>e34b15e3-3df0-4117-95dc-b9dbbb85ec68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='account_id_holder']/div/select</value>
      <webElementGuid>942a526a-c516-448d-bf8f-b0f976f7bb4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>77ef1d73-111b-4dee-8b85-af839309792d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'account_id' and @id = 'ffInput_account_id' and (text() = 'huybankhuybank tài khoản tiết kiệmVí tiền mặt' or . = 'huybankhuybank tài khoản tiết kiệmVí tiền mặt')]</value>
      <webElementGuid>28bc84bf-3a99-48d0-bf97-fbf0cb01e3d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
