<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_No auto-budgetSet a fixed amount eve_005aeb</name>
   <tag></tag>
   <elementGuidId>c9fccb66-b662-4757-8f15-9a3be6c24522</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_auto_budget_type']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_auto_budget_type</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b94851f5-14be-4ad5-8510-3168f7da783a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>dbe834ff-b2ba-44dc-b0e3-5c5a99187bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>auto_budget_type</value>
      <webElementGuid>2759991d-ed41-4516-9a48-55d51265f775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_auto_budget_type</value>
      <webElementGuid>c39ae513-f4ac-42e6-8846-fb0c50b772cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ab82f85c-7914-4e52-a1bb-29c6b332be34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dae63a7d-4079-425f-afdf-5d7b5874d5a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No auto-budgetSet a fixed amount every periodAdd an amount every periodAdd an amount every period and correct for overspending</value>
      <webElementGuid>e2833cdd-fe40-4636-a61c-f23c739de633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_auto_budget_type&quot;)</value>
      <webElementGuid>146f9dc2-0f3f-432d-920d-cca9e9fa8042</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_auto_budget_type']</value>
      <webElementGuid>888dcc2b-6d1e-4d7a-833e-b85cd81a6ead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='auto_budget_type_holder']/div/select</value>
      <webElementGuid>31485f0c-2956-44e5-b3a6-df34636626d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>692f15be-c2e3-4548-9c51-7f790866a610</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'auto_budget_type' and @id = 'ffInput_auto_budget_type' and (text() = 'No auto-budgetSet a fixed amount every periodAdd an amount every periodAdd an amount every period and correct for overspending' or . = 'No auto-budgetSet a fixed amount every periodAdd an amount every periodAdd an amount every period and correct for overspending')]</value>
      <webElementGuid>1fe5fe77-a0ff-4dfc-bb92-a397ec0d48b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
