<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_DailyWeeklyMonthlyQuarterlyEvery hal_69941c</name>
   <tag></tag>
   <elementGuidId>e1e53870-e821-452b-aa40-7258d6c14f98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_auto_budget_period']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_auto_budget_period</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>01ff8383-d571-4105-be33-c62a2fb258f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8a1d0758-5707-4179-b315-aeb385a2b730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>auto_budget_period</value>
      <webElementGuid>0c1421cb-2577-4b72-88ac-c88b8a1e4bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_auto_budget_period</value>
      <webElementGuid>ff3c6bb1-afef-4d69-9007-ce9e37a91f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e60014db-1407-4821-bbab-869871f4d41b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0f288319-7336-4f85-981b-d30c30aea218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DailyWeeklyMonthlyQuarterlyEvery half yearYearly</value>
      <webElementGuid>ee0db31c-3e09-4d39-b488-58e112fd321d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_auto_budget_period&quot;)</value>
      <webElementGuid>35a410db-868d-4c2d-8745-c3a92c600212</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_auto_budget_period']</value>
      <webElementGuid>9e16c43f-742d-4fad-9b87-de6c8c936acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='auto_budget_period_holder']/div/select</value>
      <webElementGuid>94726500-a824-4918-9bf5-dae8a493015e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>ea529673-406a-42d3-ad13-dbcac661862d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'auto_budget_period' and @id = 'ffInput_auto_budget_period' and (text() = 'DailyWeeklyMonthlyQuarterlyEvery half yearYearly' or . = 'DailyWeeklyMonthlyQuarterlyEvery half yearYearly')]</value>
      <webElementGuid>6654a669-7cd4-4de9-b558-7a26f6e4223a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
