<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Rules</name>
   <tag></tag>
   <elementGuidId>f3e27599-4145-4f8f-9d37-91b99e34df80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/aside/section/ul/li[8]/ul/li/a/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.treeview.menu-open > ul.treeview-menu > li > a > span:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c621443a-2a57-4731-b4c0-a284cc6ef9e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rules</value>
      <webElementGuid>53fe422a-c5be-4a91-8248-28e14978ab98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/aside[@class=&quot;main-sidebar&quot;]/section[@class=&quot;sidebar&quot;]/ul[@class=&quot;sidebar-menu tree&quot;]/li[@class=&quot;treeview menu-open&quot;]/ul[@class=&quot;treeview-menu&quot;]/li[1]/a[1]/span[2]</value>
      <webElementGuid>9763ee2b-dc87-4ee9-84d1-7ff401894f47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/aside/section/ul/li[8]/ul/li/a/span[2]</value>
      <webElementGuid>4d298268-dadf-4733-be91-2524017ac316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/ul/li/a/span[2]</value>
      <webElementGuid>6aa670d3-a72f-4d49-887e-eab8565cff0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Rules' or . = 'Rules')]</value>
      <webElementGuid>ab9cf10f-2d50-4d09-aa85-7513ad4697ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
