<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_triggers1stop_processing</name>
   <tag></tag>
   <elementGuidId>caf70dfb-3c36-48ba-b7ab-d1a9856b6411</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='triggers[1][stop_processing]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;triggers[1][stop_processing]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>631142e3-e1b2-4307-a2dd-0728ec52f0ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2fb10a64-d907-4423-ba2d-730635fe6491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>trigger-stop-processing</value>
      <webElementGuid>7b94e662-dd79-4548-89d4-f4a0238c3994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>triggers[1][stop_processing]</value>
      <webElementGuid>b3219c08-0649-474d-8a31-9800659da4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f68d3b97-4a76-45b5-9ed9-c7ca4af3f781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;store&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;box-body rule-trigger-box&quot;]/table[@class=&quot;table table-condensed table-bordered table-striped&quot;]/tbody[@class=&quot;rule-trigger-tbody&quot;]/tr[@class=&quot;rule-trigger-holder&quot;]/td[5]/div[@class=&quot;checkbox&quot;]/label[1]/input[@class=&quot;trigger-stop-processing&quot;]</value>
      <webElementGuid>162eab8b-e36b-4ab3-aaa7-a2b6a3c352df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='triggers[1][stop_processing]']</value>
      <webElementGuid>53341ac7-f552-404c-84dd-7ff1bd30dedd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='store']/div[2]/div/div/div[2]/table/tbody/tr/td[5]/div/label/input</value>
      <webElementGuid>66788900-e9b5-4882-9b52-08015b93534e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/label/input</value>
      <webElementGuid>97b921a1-bfd2-4f0c-a0ae-c00cf7dd8e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'triggers[1][stop_processing]']</value>
      <webElementGuid>67786121-7e40-468b-ae59-4ae8c12cd1ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
