<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_actions1stop_processing</name>
   <tag></tag>
   <elementGuidId>019db59f-a0fb-4a3f-ac2b-3a4d6ba2e8a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='actions[1][stop_processing]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;actions[1][stop_processing]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c74e7f3-435c-4790-a8d9-c987050d7e1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2bf0b8a0-24cf-4093-993a-ad3cff91ac87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>actions[1][stop_processing]</value>
      <webElementGuid>d34e602b-4362-4dd7-9ff3-869bdbcc939a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2ca05938-ef12-4763-a24d-77dbf0e80882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;store&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-md-12 col-sm-12&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;box-body rule-action-box&quot;]/table[@class=&quot;table table-condensed table-bordered table-striped&quot;]/tbody[@class=&quot;rule-action-tbody&quot;]/tr[@class=&quot;rule-action-holder&quot;]/td[4]/div[@class=&quot;checkbox&quot;]/label[1]/input[1]</value>
      <webElementGuid>843ebb65-e297-4da5-8899-c862acc33a62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='actions[1][stop_processing]']</value>
      <webElementGuid>5eb1115b-8238-4387-9856-4a614f9d34c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='store']/div[4]/div/div/div[2]/table/tbody/tr/td[4]/div/label/input</value>
      <webElementGuid>05bc1be7-e811-4676-9306-f9bd197cb763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/label/input</value>
      <webElementGuid>32234d48-3baf-47b9-a644-b7fcaf8bdbcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'actions[1][stop_processing]']</value>
      <webElementGuid>c37ad3b9-cb3a-488d-a243-b24cb9c57421</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
