<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_stop_processing</name>
   <tag></tag>
   <elementGuidId>3f961ec6-04aa-47e1-bb82-31c64a320c05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ffInput_stop_processing']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_stop_processing</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4188da88-8ead-4d91-b196-19a742e8bf85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>44f5f30c-d9f6-4ac3-b4c7-ab429a27b9ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>stop_processing</value>
      <webElementGuid>2a55b562-4b6a-458c-8ecd-86de346fdb9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_stop_processing</value>
      <webElementGuid>41d05f99-0fc3-4f3b-97e5-f9e98a977350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>90b414a1-993e-488d-b3b1-1fea1319ac4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_stop_processing&quot;)</value>
      <webElementGuid>32651fb0-48dc-43ac-a017-57d4f0a5ffa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ffInput_stop_processing']</value>
      <webElementGuid>7f22dde6-eab0-4cdf-99e6-cfe4e688251f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='stop_processing_holder']/div/div/label/input</value>
      <webElementGuid>fb4b3fb6-787e-46e0-abf5-21fdaffbf7de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>33248169-3256-410a-af8b-d5344ca77b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'stop_processing' and @id = 'ffInput_stop_processing']</value>
      <webElementGuid>fa60f3ed-5d10-488b-b8de-4931d6c9879d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
