<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_trigger_when</name>
   <tag></tag>
   <elementGuidId>a56fcb2f-49ca-468b-bd53-6dcd28fd3a6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_trigger']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_trigger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>78b36414-6364-4f9d-af52-e317d8a88713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>188e1e18-1f73-4b13-abf4-2428e78e93b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>trigger</value>
      <webElementGuid>1d3cbf44-c45d-4bbd-b012-ea6255c22f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_trigger</value>
      <webElementGuid>3d571049-fac8-4b7c-9095-f5aa4c76e028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>25e197cd-b59b-48f5-8256-5d4a55e018a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6fd3a36c-de8e-4ac8-846f-a3ef26928602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>When a transaction is createdWhen a transaction is updated</value>
      <webElementGuid>0eb037b2-1306-4191-88b2-49ebe5649ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_trigger&quot;)</value>
      <webElementGuid>8cae50d4-99b4-4826-a26b-25ad4250c928</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_trigger']</value>
      <webElementGuid>a4ebcb98-8aed-4748-acab-a5d0077ad2c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trigger_holder']/div/select</value>
      <webElementGuid>47139ebc-80c6-48c3-8036-c2d1a1b8f4d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>7d2ac41e-f8c5-4c85-8385-ed5e8e7776bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'trigger' and @id = 'ffInput_trigger' and (text() = 'When a transaction is createdWhen a transaction is updated' or . = 'When a transaction is createdWhen a transaction is updated')]</value>
      <webElementGuid>8814584d-148f-4312-a71c-3704ff81a71e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
