<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_rule_group</name>
   <tag></tag>
   <elementGuidId>59dda215-be72-4823-ab97-9965baf517a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_rule_group_id']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ffInput_rule_group_id</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e801699f-c0ae-437b-bc5d-0f7685a78743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>9db53207-5347-4a79-b4d7-6a362a95360c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>rule_group_id</value>
      <webElementGuid>9b33d2d9-4d2d-4c7d-b747-98565bf65132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_rule_group_id</value>
      <webElementGuid>3b1984fb-01fd-465d-8836-c481ba6d5897</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>20755fdd-581e-4354-8dcf-ce0af76a8347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c6fae369-cdd9-4c3f-9d2e-2ccfbddbfae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Default rulesSaving</value>
      <webElementGuid>e69bab6c-c832-436d-93ba-dc7c6b717eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_rule_group_id&quot;)</value>
      <webElementGuid>30749301-75fd-4347-86b3-92cb4bcc55a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_rule_group_id']</value>
      <webElementGuid>f409a7ac-4c85-431b-83dd-264f2701f7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rule_group_id_holder']/div/select</value>
      <webElementGuid>73c46f86-5362-4dac-b2a0-1785a66bcc53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>e9d4eb1a-526e-4a9e-889f-b84c64786933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'rule_group_id' and @id = 'ffInput_rule_group_id' and (text() = 'Default rulesSaving' or . = 'Default rulesSaving')]</value>
      <webElementGuid>8eda583e-66d1-4317-9268-50b69a1bef99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
