<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Transactions</name>
   <tag></tag>
   <elementGuidId>d185e55d-f8ab-4f05-9c5c-16f6da8a5063</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='transaction-menu']/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#transaction-menu > a > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0fd5634c-b6a5-4746-b37f-f07db16cb262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transactions</value>
      <webElementGuid>50d4c709-47d8-45c5-b950-515b6d0a0d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transaction-menu&quot;)/a[1]/span[1]</value>
      <webElementGuid>5bdc974a-9c3c-4739-89d5-eef71fed3dee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='transaction-menu']/a/span</value>
      <webElementGuid>942fe424-9e8b-4eac-877b-ad21a1fb03b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a/span</value>
      <webElementGuid>df0fd7d2-7267-433d-8926-170baea0077f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Transactions' or . = 'Transactions')]</value>
      <webElementGuid>0b589ce1-ad29-4a11-bf96-e8ef9f017ca6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
