<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_huybank</name>
   <tag></tag>
   <elementGuidId>9bf8ce61-8f28-4934-acb9-790949649e7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='extra-options']/div/div/span/div/ul/li[3]/a/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(3) > a > label.checkbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>81965a4c-5da1-4495-8f97-3e109d589bc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1cbebe5a-8578-44ba-99fa-b64da4a1eab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> huybank</value>
      <webElementGuid>ad0e875c-9500-46d9-b8ea-54b6516c8729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;extra-options&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-9&quot;]/span[@class=&quot;multiselect-native-select&quot;]/div[@class=&quot;btn-group open&quot;]/ul[@class=&quot;multiselect-container dropdown-menu&quot;]/li[3]/a[1]/label[@class=&quot;checkbox&quot;]</value>
      <webElementGuid>74587d18-53a2-4c22-9bf3-2013482c1933</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='extra-options']/div/div/span/div/ul/li[3]/a/label</value>
      <webElementGuid>02a0e89c-42e1-4f00-872e-e274996a80c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/span/div/ul/li[3]/a/label</value>
      <webElementGuid>2673eccb-dd63-49cc-bc94-294620a6c02d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = ' huybank' or . = ' huybank')]</value>
      <webElementGuid>33560079-bea5-4ad3-bc97-638875cd16b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
