<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ti-new-tag-input ti-valid</name>
   <tag></tag>
   <elementGuidId>9571063a-afda-450e-bb9b-8b315f4e4274</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.ti-new-tag-input.ti-valid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d39c4803-3052-401f-a2e4-648f8b1e95a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Tags</value>
      <webElementGuid>6d4ad623-3fca-4343-818b-0f85ceb5aee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8de625fa-80ae-46f6-8d3d-f30323fecf22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>734e7cc0-ec2a-4a44-872a-6102a3ae6a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Tags</value>
      <webElementGuid>a9ac41b8-280d-402f-90d2-83523f164a15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ti-new-tag-input ti-valid</value>
      <webElementGuid>ff53db74-8955-4d0d-8979-1cdba89d4ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optional-info&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;input-group&quot;]/div[@class=&quot;vue-tags-input force-background-tags-input ti-focus&quot;]/div[@class=&quot;ti-input&quot;]/ul[@class=&quot;ti-tags&quot;]/li[@class=&quot;ti-new-tag-input-wrapper&quot;]/input[@class=&quot;ti-new-tag-input ti-valid&quot;]</value>
      <webElementGuid>c5dd51cd-62cc-4fe5-8599-5e462cdb6c8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[6]</value>
      <webElementGuid>fb4292d4-c3b3-4860-84f3-432f9bc45dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='optional-info']/div[4]/div[2]/div/div/div/ul/li/input</value>
      <webElementGuid>42b378b2-6147-4a5b-b5d7-72a4f05280e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/input</value>
      <webElementGuid>05d5b32b-8cfb-499d-90b4-a6a1c81499e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Tags' and @type = 'text' and @title = 'Tags']</value>
      <webElementGuid>07a0a72c-b5c3-47b2-b934-521a14a8af7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
