<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(none)</name>
   <tag></tag>
   <elementGuidId>e02abc34-4474-40b8-9530-cec2763f1123</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='bill[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;bill[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ce0a1051-efdb-4a41-861d-b5eb4a81cd4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Bill</value>
      <webElementGuid>1644fe54-a920-4cb0-8e64-3ca9ba0b230e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bill[]</value>
      <webElementGuid>1668708e-069d-4f96-8892-4efe30e62eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b7aaf9fb-c428-4266-a3ab-139c22b48d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(none)
      </value>
      <webElementGuid>cf0f112c-da15-4a01-95a9-dddb071e92b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optional-info&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-12&quot;]/select[@class=&quot;form-control&quot;]</value>
      <webElementGuid>72ed46f6-8663-4f57-956d-fa7325eb8b28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='bill[]']</value>
      <webElementGuid>9e7d4165-7e37-4735-a3a2-ecdb5aae1a62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='optional-info']/div[5]/div[2]/select</value>
      <webElementGuid>6edab51f-a4c0-419d-a294-5e1eecf60b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/select</value>
      <webElementGuid>0cd4e144-3715-41fd-9559-0c692ae4ad01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@title = 'Bill' and @name = 'bill[]' and (text() = '(none)
      ' or . = '(none)
      ')]</value>
      <webElementGuid>c4168cbf-f262-4602-9af4-0d15f21faf9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
