<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_notes</name>
   <tag></tag>
   <elementGuidId>2d7386a5-c36b-4d40-9235-02ff640faf5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='notes[]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;notes[]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ba304369-3690-4f61-9368-f8f38b6c4df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>notes[]</value>
      <webElementGuid>aa7b9a87-46bc-4b95-935d-a36879d579dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>42c10a4d-5ef0-4022-9b08-6cd1258cd3c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Notes</value>
      <webElementGuid>333e18de-0783-4476-82fa-03b606595daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b5ba9d53-20ae-4baa-8a2d-0347ee0d753a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>c0532360-bda2-45ad-bd5f-c5d4072870b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>eb15fb5a-4688-4c90-9c67-faf7c166e417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;optional-info&quot;)/div[6]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-12&quot;]/textarea[@class=&quot;form-control&quot;]</value>
      <webElementGuid>d71e74b5-f6a0-4e34-abe8-46a1bc19a772</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='notes[]']</value>
      <webElementGuid>b9d25fcb-ce48-4e1e-b23f-d3cbd1cbddb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='optional-info']/div[6]/div[3]/div[2]/textarea</value>
      <webElementGuid>43c318c3-def8-4038-a859-5c6e4325671e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>03cf0f70-7547-4a83-88ad-01c630e69b04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'notes[]' and @placeholder = 'Notes' and @title = 'Notes']</value>
      <webElementGuid>d465990c-925c-407d-8870-c6fdc06164be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
